blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ROYCE-8425/quiz_study/blob/main/docs/development/build-from-source.md
    about: Check the build and development documentation
  - name: GitHub Discussions
    url: https://github.com/ROYCE-8425/quiz_study/discussions
    about: Share ideas and discuss with the community
